name: Release

on: workflow_dispatch

env:
  NODEVERSION: 18.x
  PNPM_VERSION: 8.6.0

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEVERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build && pnpm build:esm
      - run: ./scripts/resolveVersion.sh # replace the constant VERSION with correct value
      - run: pnpm publish --access public --filter "./packages/**"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
